---
title: "Hest"
output:
  html_document: default
  pdf_document: default
date: '2023-01-07'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("caret")
library("caTools")
library("party")
library("dplyr")
library("rpart.plot")
library("Ecdat")
library("RWeka")
install.packages("RWeka")
system("java -version")

```

```{r}
data = read.table("horse_data23.txt", header = TRUE)
head(data)

dim(data)
```

```{r}
experiment = data$experiment
horse = data$horse
lLeg = data$lameLeg
lSide = data$lameSide
lFrHind = data$lameForeHind

A = data$A
S = data$S
W = data$W

pc1 = data$pc1
pc2 = data$pc2
pc3 = data$pc3
pc4 = data$pc4
```

### Plots:

```{r}
#png('QQplots.png', height = 480, width = 480*2)
par(mfrow = c(1,3))

qqnorm(A, main = "QQPlot: A")
qqline(A)
qqnorm(W, main = "QQPlot: W")
qqline(W)
qqnorm(S, main = "QQPlot: S")
qqline(S)
```

```{r}
A1 = rep(NA, length(data$A))
A2 = rep(NA, length(data$A))
A3 = rep(NA, length(data$A))
A4 = rep(NA, length(data$A))
A5 = rep(NA, length(data$A))

for (i in 1:length(data$A)){
  if (data$lameSide[i] == "right" & lFrHind[i] == "hind"){
    A1[i] = data$A[i]
  }
  
  if (data$lameSide[i] == "right" & lFrHind[i] == "fore"){
    A2[i] = data$A[i]
  }
  
  if (data$lameSide[i] == "left" & lFrHind[i] == "hind"){
    A3[i] = data$A[i]
  }
  
  if (data$lameSide[i] == "left" & lFrHind[i] == "fore"){
    A4[i] = data$A[i]
  }
  
  if (data$lameSide[i] == "none"){
    A5[i] = data$A[i]
  }
}

#png('A_box.png')
boxplot(A1, A2, A3, A4, A5, ylab = "A", xlab = "Lameness", col = c(2,3,4,5,6))
legend("bottomleft", inset=.02, title="Lameness",
   c("right hind","right fore","left hind", "left fore", "none"), fill=c(2,3,4,5,6), horiz=TRUE, cex=0.6)

#png('A_plot.png')
plot(A1, col = 2, axes = TRUE, ylab = "A", xlim =c(0, 85), ylim =c(-2, 2), pch = 1)
par(new = TRUE)
plot(A2, col = 3, axes = FALSE, ylab = "A", xlim =c(0, 85), ylim =c(-2, 2), pch = 1)
par(new = TRUE)
plot(A3, col = 4, axes = FALSE, ylab = "A", xlim =c(0, 85), ylim =c(-2, 2), pch = 2)
par(new = TRUE)
plot(A4, col = 5, axes = FALSE, ylab = "A", xlim =c(0, 85), ylim =c(-2, 2), pch = 2)
par(new = TRUE)
plot(A5, col = 6, axes = FALSE, ylab = "A", xlim =c(0, 85), ylim =c(-2, 2), pch = 3)
legend(x = "topleft", pch = c(1,1,2,2,3), text.font = 2, 
       col= c(2,3,4,5,6), text.col = "black", 
       legend=c("right hind","right fore","left hind", "left fore", "none"))
```

```{r}
W1 = rep(NA, length(data$W))
W2 = rep(NA, length(data$W))
W3 = rep(NA, length(data$W))
W4 = rep(NA, length(data$W))
W5 = rep(NA, length(data$W))

for (i in 1:length(data$A)){
  if (data$lameSide[i] == "right" & lFrHind[i] == "hind"){
    W1[i] = data$W[i]
  }
  
  if (data$lameSide[i] == "right" & lFrHind[i] == "fore"){
    W2[i] = data$W[i]
  }
  
  if (data$lameSide[i] == "left" & lFrHind[i] == "hind"){
    W3[i] = data$W[i]
  }
  
  if (data$lameSide[i] == "left" & lFrHind[i] == "fore"){
    W4[i] = data$W[i]
  }
  
  if (data$lameSide[i] == "none"){
    W5[i] = data$W[i]
  }
}

#png('W_box.png')
boxplot(W1, W2, W3, W4, W5, ylab = "W", xlab = "Lameness", col = c(2,3,4,5,6))
legend("topleft", inset=.02, title="Lameness",
   c("right hind","right fore","left hind", "left fore", "none"), fill=c(2,3,4,5,6), horiz=TRUE, cex=0.6)

#png('W_plot.png')
plot(W1, col = 2, axes = TRUE, ylab = "W", xlim =c(0, 85), ylim =c(-0.2, 0.2), pch = 1)
par(new = TRUE)
plot(W2, col = 3, axes = FALSE, ylab = "W", xlim =c(0, 85), ylim =c(-0.2, 0.2), pch = 1)
par(new = TRUE)
plot(W3, col = 4, axes = FALSE, ylab = "W", xlim =c(0, 85), ylim =c(-0.2, 0.2), pch = 2)
par(new = TRUE)
plot(W4, col = 5, axes = FALSE, ylab = "W", xlim =c(0, 85), ylim =c(-0.2, 0.2), pch = 2)
par(new = TRUE)
plot(W5, col = 6, axes = FALSE, ylab = "W", xlim =c(0, 85), ylim =c(-0.2, 0.2), pch = 3)
legend(x = "topleft", pch = c(1,1,2,2,3), text.font = 2, 
       col= c(2,3,4,5,6), text.col = "black", 
       legend=c("right hind","right fore","left hind", "left fore", "none"))
```

```{r}
S1 = rep(NA, length(data$S))
S2 = rep(NA, length(data$S))
S3 = rep(NA, length(data$S))
S4 = rep(NA, length(data$S))
S5 = rep(NA, length(data$S))

for (i in 1:length(data$S)){
  if (data$lameSide[i] == "right" & lFrHind[i] == "hind"){
    S1[i] = data$S[i]
  }
  
  if (data$lameSide[i] == "right" & lFrHind[i] == "fore"){
    S2[i] = data$S[i]
  }
  
  if (data$lameSide[i] == "left" & lFrHind[i] == "hind"){
    S3[i] = data$S[i]
  }
  
  if (data$lameSide[i] == "left" & lFrHind[i] == "fore"){
    S4[i] = data$S[i]
  }
  
  if (data$lameSide[i] == "none"){
    S5[i] = data$S[i]
  }
}

#png('S_box.png')
boxplot(S1, S2, S3, S4, S5, ylab = "S", xlab = "Lameness", col = c(2,3,4,5,6))
legend("bottomleft", inset=.02, title="Lameness",
   c("right hind","right fore","left hind", "left fore", "none"), fill=c(2,3,4,5,6), horiz=TRUE, cex=0.6)

#png('S_plot.png')
plot(S1, col = 2, axes = TRUE, ylab = "S", xlim =c(0, 85), ylim =c(-8, -1), pch = 1)
par(new = TRUE)
plot(S2, col = 3, axes = FALSE, ylab = "S", xlim =c(0, 85), ylim =c(-8, -1), pch = 1)
par(new = TRUE)
plot(S3, col = 4, axes = FALSE, ylab = "S", xlim =c(0, 85), ylim =c(-8, -1), pch = 2)
par(new = TRUE)
plot(S4, col = 5, axes = FALSE, ylab = "S", xlim =c(0, 85), ylim =c(-8, -1), pch = 2)
par(new = TRUE)
plot(S5, col = 6, axes = FALSE, ylab = "S", xlim =c(0, 85), ylim =c(-8, -1), pch = 3)
legend(x = "topleft", pch = c(1,1,2,2,3), text.font = 2, 
       col= c(2,3,4,5,6), text.col = "black", 
       legend=c("right hind","right fore","left hind", "left fore", "none"))
```

### P-values:

```{r}
A_norm = (A-mean(A))/sd(A)
W_norm = (W-mean(W))/sd(W)
PC3_norm = (pc3-mean(pc3))/sd(pc3)
PC4_norm = (pc4-mean(pc4))/sd(pc4)
```

```{r}
horses = as.factor(horse)
lameness = as.factor(lLeg)


fit = lm(A ~ horses)
anova(fit)

fit = lm(W ~ horses)
anova(fit)

fit = lm(S ~ horses)
anova(fit)

fit = lm(A + W + S ~ horses)
anova(fit)

fit = lm(A * W * S ~ horses)
anova(fit)
```

```{r}
n = 1e3
split = 1/4

MSE_A = rep(NA, n)
MSE_W = rep(NA, n)
MSE_PC3 = rep(NA, n)
MSE_PC4 = rep(NA, n)

for (i in 1:n){
  set.seed(100 + i)
  sample = sample(c(TRUE, FALSE), nrow(data), replace=TRUE, prob = c(1-split, split))
  train_A = A_norm[sample]
  test_A = A_norm[!sample]

  train_W = W_norm[sample]
  test_W = W_norm[!sample]

  train_PC3 = PC3_norm[sample]
  test_PC3 = PC3_norm[!sample]

  train_PC4 = PC4_norm[sample]
  test_PC4 = PC4_norm[!sample]
  
  # Baseline (A/W)
  MSE_A[i] = mean((test_A-mean(train_A))**2)
  MSE_W[i] = mean((test_W-mean(train_W))**2)
  
  # Baseline (PC3/PC4)
  MSE_PC3[i] = mean((test_PC3-mean(train_PC3))**2)
  MSE_PC4[i] = mean((test_PC4-mean(train_PC4))**2)
  
}

fit_AW = lm(train_A ~ train_W)
alpha_AW = fit_AW$coefficients[1]
beta_AW = fit_AW$coefficients[2]
train_AW = alpha_AW + train_W*beta_AW
test_AW = alpha_AW + test_W*beta_AW
trainError_AW = mean((train_A-train_AW)^2)
testError_AW = mean((test_A-test_AW)^2)


fit_PC34 = lm(train_PC3 ~ train_PC4)
alpha_PC34 = fit_PC34$coefficients[1]
beta_PC34 = fit_PC34$coefficients[2]

head((c(MSE_A, MSE_W)))
head((c(MSE_PC3, MSE_PC4)))
```

```{r}
n = 1e3
split = 1/4

trainError_AW = rep(NA, n)
testError_AW = rep(NA, n)
trainError_PC34 = rep(NA, n)
testError_PC34 = rep(NA, n)

for (i in 1:n){
  set.seed(100 + i)
  sample = sample(c(TRUE, FALSE), nrow(data), replace=TRUE, prob = c(1-split, split))
  train_A = A_norm[sample]
  test_A = A_norm[!sample]

  train_W = W_norm[sample]
  test_W = W_norm[!sample]

  train_PC3 = PC3_norm[sample]
  test_PC3 = PC3_norm[!sample]

  train_PC4 = PC4_norm[sample]
  test_PC4 = PC4_norm[!sample]
  
  # Baseline (A/W)
  fit_AW = lm(train_A ~ train_W)
  
  alpha_AW = fit_AW$coefficients[1]
  beta_AW = fit_AW$coefficients[2]
  
  train_AW = alpha_AW + train_W*beta_AW
  test_AW = alpha_AW + test_W*beta_AW
  
  trainError_AW[i] = mean((train_A-train_AW)^2)
  testError_AW[i] = mean((test_A-test_AW)^2)
  
  # Baseline (PC3/PC4)
  fit_PC34 = lm(train_PC3 ~ train_PC4)
  
  alpha_PC34 = fit_PC34$coefficients[1]
  beta_PC34 = fit_PC34$coefficients[2]
  
  train_PC34 = alpha_PC34 + train_PC4*beta_PC34
  test_PC34 = alpha_PC34 + test_PC4*beta_PC34
  
  trainError_PC34[i] = mean((train_PC3-train_PC34)^2)
  testError_PC34[i] = mean((test_PC3-test_PC34)^2)
}

c(head(testError_AW), head(testError_PC34))
```

```{r}
ctrl = trainControl(method = "LOOCV")
fit = lLeg ~ A
summary(fit)
model = train(fit, data = as.data.frame(data[6:8]), method = "LMT", trControl = ctrl)
data

data[6:8]

print(model)

sample_data = sample.split(A, SplitRatio = 0.8)
train_A = subset(A, train == TRUE)
test_A = subset(A, train == FALSE)
train_W = subset(W, train == TRUE)
test_W = subset(W, train == FALSE)

train_A
test_A

data_train = create_train_test(clean_titanic, 0.8, train = TRUE)

fit = rpart(as.factor(lLeg)~A, data = data, method = 'class')
fit
plot(fit)
```

```{r}
pred = predict(fit)

m_at = table(train_A, pred)
m_at
```

```{r}
par(mfrow = c(2,4))
hist(trainError_AW)
hist(testError_AW)
hist(trainError_PC34)
hist(testError_PC34)

boxplot(trainError_AW)
boxplot(testError_AW)
boxplot(trainError_PC34)
boxplot(testError_AW)
```

```{r}
#png("baselineplots.png")
par(mfrow = c(2,4))

hist(MSE_A, nclass = 50, main = "MSE: A")
hist(MSE_W, nclass = 50, main = "MSE: W")
hist(MSE_PC3, nclass = 50, main = "MSE: PC3")
hist(MSE_PC4, nclass = 50, main = "MSE: PC4")

boxplot(MSE_A)
boxplot(MSE_W)
boxplot(MSE_PC3)
boxplot(MSE_PC4)
```

```{r}
par(mfrow=(c(1,2)))
boxplot(A_norm, W_norm)
boxplot(PC3_norm, PC4_norm)

par(mfrow=(c(1,2)))
plot(A_norm, W_norm)
plot(PC3_norm, PC4_norm)
```
